name: Code Quality Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: One Version Check
      run: bun run one-version:check

    - name: Run tests
      run: bun run test

    - name: Run lints
      run: bun run lint

    - name: Run type-checks
      run: bun run type-check

    - name: Check formatting
      run: bun run format:check
